const Map<String, String> en = {
  'Error': 'Error',
  'Hello, From App': 'Hello, From App',
  'Whats App Error': 'Whats App Error',
  'Install WhatsApp First Please': 'Install WhatsApp First Please',
  'Select Language': 'اختر اللغة',
  'Product has been deleted': 'The product has been deleted',
  'Default': 'Default',
  'Newest': 'Newest',
  'Most Popular': 'Most Popular',
  'Low to High': 'Low to High',
  'High to Low': 'High to Low',
  'خطأ': 'Error',
  'مرحباً، من التطبيق': 'Hello, From App',
  'خطأ واتساب': 'Whats App Error',
  'يرجى تثبيث الواتساب أولاً': 'Install WhatsApp First Please',
  'المنتج تم حذفه': 'The product has been deleted',
  'الأفتراضي': 'Default',
  'الأحدث': 'Newest',
  'الأكثر شعبية': 'Most Popular',
  'الأقل سعر': 'Low to High',
  'الأعلى سعر': 'High to Low',
  'حسابي': 'Account',
  'أهلا بك ': 'Welcome ',
  'خروج': 'Logout',
  'تسجيل / دخول مستخدم': 'Register / Login',
  'تعديل الملف الشخصي': 'Edit Profile',
  'عنواني': 'My Address',
  'لغة التطبيق': 'Application language',
  'العربية': 'English',
  'من نحن': 'About Us',
  'سياسة الخصوصية والاستخدام': 'Privacy Policy and Use',
  'خيارات الدفع والتوصيل': 'Payment and delivery options',
  'سياسة الإستبدال والاسترجاع': 'Return and Refund Policy',
  'الصفحات الإضافية': 'Additional pages',
  'شبكاتنا': 'Social Media',
  'تواصل معنا': 'Connect with us',
  'واتس اب': 'Whatsapp',
  'اتصال': 'Contact',
  'ايميل': 'Email',
  'تطوير': 'Developed by ',
  'يرجى ادخال رمز الكوبون': 'Please enter the coupon code',
  'يرجى اختيار جميع الخيارات': 'Please select all options',
  'تم اضافة المنتج إلى السلة': 'The product has been added to cart',
  'السلة': 'Cart',
  'كوبون الخصم': 'Discount Coupon',
  'أضف كوبون': 'Add Coupon',
  'أدخل الكوبون': 'Enter the coupon',
  'حذف': 'Delete',
  'تطبيق الكوبون': 'Apply',
  'تم خصم ': 'Coupon discounted ',
  'الإجمالي': 'Total',
  'إتمام الدفع': 'Purchase',
  'لم تقم بإضافة أي منتج للسلة': 'The cart is empty',
  ' مدن': 'Cities ',
  'خيارات الشحن': 'Shipping options',
  'المدن التي يتم تغطيتها': 'Cities that are covered',
  'تكلفة الشحن': 'Shipping charges',
  'الدفع عند الإستلام': 'Cash on delivery',
  'أضف تعليق': 'Add comment',
  'لا تظهر اسمي في قائمة العملاء': 'My name does not appear in the client list',
  'قيم المنتج': 'Rate the product',
  'اكتب تعليقك هنا': 'Write your comment here',
  'إرسال': 'Submit',
  'السعر': 'Price',
  'إعادة ضبط': 'Reset',
  'من': 'From',
  'إلى': 'To',
  'ر.س': 'SAR',
  'تصفية': 'Filter',
  'تعديل الحساب': 'Edit Account',
  'الاسم': 'Full name',
  'البريد الإلكتروني': 'Email',
  'رقم الجوال': 'Mobile',
  'حفظ التغييرات': 'Save',
  'عرض الكل': 'More',
  'نفذت الكمية': 'Out of Stock',
  'خصم ': 'Discount ',
  'أضف للسلة': 'Add to cart',
  'سجل دخولك': 'Login',
  'طلب رمز التفعيل': 'Request activation code',
  'القائمة': 'Menu',
  'طرق الدفع': 'Payment Method',
  'الرقم الضريبي': 'VAT Number',
  'المتجر': 'Home',
  'التصنيفات': 'Categories',
  'طلباتي': 'Orders',
  'الإشعارات': 'Notifications',
  'لا توجد اشعارات في الوقت الحالي': 'No notifications at the moment',
  'تفاصيل الطلب': 'Order details',
  'رقم الطلب: #': 'Order id #',
  'بإنتظار إتمام الدفع لتجهيز طلبك، لإتمام الدفع ومعرفة معلومات الحساب البنكي':
      'Wait for payment to process your order, To complete your payment and find out your bank account information ',
  'إضغط هنا': 'Press here',
  'المنتجات': 'Products',
  'طريقة التوصيل': 'Shipping method',
  'تاريخ إنشاء الطلب': 'Orders creation date',
  'طريقة الدفع': 'Payment method',
  'الحالة': 'Status',
  'ادفع': 'Pay',
  'التوصيل': 'Delivery',
  'الدولة': 'Country',
  'المدينة': 'City',
  'الحي': 'District',
  'الشارع': 'Street',
  'يرجى تسجيل الدخول أولاً': 'Please Login First',
  'رقم الطلب': 'Order Number',
  'تم التسليم': 'Delivered',
  'اختر': 'Choose',
  'رمز التفعيل': 'Verification code',
  'تم إرسال رمز التفعيل للرقم ':
      'A text message has been sent with the verification code to your mobile',
  'رمز التفعيل المدخل غير صحيح': 'Invalid verification code',
  'لم يصلك الرمز؟ طلب مرة أخرى': 'Did not receive the verification code',
  'تأكيد ودخول': 'Confirm and login',
  'يرجى ادخال البريد الإلكتروني': 'Please enter email',
  'البريد الالكتروني غير صالح': 'Invalid email',
  'تم تفعيل التنبيه بنجاح': 'Sent successfully',
  'مشاركة': 'Share',
  'رمز المنتج: ': 'SKU: ',
  'عرض جميع التقييمات': 'View all reviews',
  'منتجات مشابهة': 'You may also like',
  'المنتج غير متوفر حالياً': 'Out of Stock',
  'أدخل بريدك الإلكتروني ليتم إعلامك عندما يتوفر مرة أخرى':
      'Notify me when product is available',
  'ارسل': 'Submit',
  'السعر ': 'Price ',
  'تم اضافة مراجعتك بنجاح': 'Your review has been submitted successfully',
  'التقييمات': 'Reviews',
  'أضف تقييم': 'Add review',
  'ابحث هنا': 'Search here',
  'لم نعثر على نتائج بحث': 'No search results found',
  'البحث': 'Search',
  'اختر الدولة': 'Select country',
  'حدد وجهة التسوق الخاصة بك': 'Select your shopping destination',
  'السعودية': 'Saudi Arabia',
  'اختر اللغة': 'Choose the language',
  'التالي': 'Next',
  'عرض تفاصيل الطلب': 'View order details',
  'تم إرسال طلبك بنجاح': 'Your order has been submitted successfully',
  'التعليق مطلوب': 'Comment Required',
  'الاسم الكامل مطلوب': 'Full name is required',
  'البريد الإلكتروني مطلوب': 'Email is required',
  'رقم الجوال مطلوب': 'Mobile number is required',
  'يجب ان يتكون الرقم من 9 أرقام': 'The number must consist of 9 digits',
  'رمز التأكيد مطلوب': 'Verification code is required',
  'يجب ان يتكون الرمز من 4 أرقام': 'The code must consist of 4 numbers',
  'كلمة المرور مطلوبة': 'Password is required',
  'بإنتظار إتمام الدفع': 'Wait for payment to process your order',
  'البنوك المتاحة للتحويل': 'Banks available for transfer: ',
  'اسم المحول له: ': 'Name: ',
  'رقم الحساب': 'Account Number ',
  'رقم الايبان': 'IBAN Number ',
  'إجمالي الطلب': 'Order total',
  'لعرض تفاصيل الطلب اضغط هنا': 'Press here to view order details',
  'اختر البنك المحول له': 'Select the bank that converts it',
  'اسم صاحب الحساب البنكي المحول منه': 'Bank account owner name',
  'تحميل صورة الحوالة': 'Download the picture of the hawala',
  'تأكيد التحويل': 'Send the transfer',
  'يرجى اختيار البنك أولاً': 'Select the bank firstً',
  'يرجى ادخال اسم المحول منه أولاً': 'Insert the name firstً',
  'يرجى ارفاق صورة الحوالة أولاً': 'upload the hawala firstً',
  'تم ارسال الحوالة بنجاح': 'Transfer sent successfully',
  'المزيد': 'view more',
  'قيمة الشحن مجانية الآن': 'Free shipping now',
  'متبقي على الشحن المجاني @discount @currency':
      '@discount @currency left on free shipping',
  'قيّم المنتج': 'Add Review',
  'نبهني عند توفر المنتج': 'Notify me',
  'حجم الملف غير صالح\nحجم الملف الأقصى : 8M': 'Invalid file size\nMaximum file size: 8M',
  'سيئ': 'Bad',
  'لم يعجبني': 'don\'t like it',
  'جيد': 'Good',
  'جيد جداً': 'Excellentً',
  'رائع': 'Wonderful',
  'نعتذر لك التطبيق لا يعمل الآن': 'Sorry, the app is not working now',
  'لا يوجد لديك طلبات سابقة': 'You have no previous orders',
  'لا يوجد تقييمات سابقة': 'There are no previous reviews',
  'المفضلة': 'Wishlist',
  'لا يوجد منتجات في القائمة، أضف منتجات لقائمة التفضيل من خلال الضغط على أيقونة':
      'There are no products in the wishlist, add products to the wishlist by pressing ',
  'في بطاقة المنتج': 'in the product card',
  'شارك التطبيق': 'Share the app',
  'تم تفعيل خصم تطبيق الجوال ': 'Mobile app discount activated ',
  'يرجى التأكد من اتصالك بالإنترنت': 'Please make sure you are connected to the internet',
  'نعتذر، لا يوجد تصنيفات حاليا': 'Sorry, there are currently no categories',
  'تسجيل الدخول عن طريق رقم الجوال': 'Login by phone number',
  'تسجيل الدخول عن طريق البريد الإلكتروني': 'Login by email',
  'تم إرسال رمز التفعيل للبريد الإلكتروني\n':
      '\nA mail message has been sent with the verification code to your email',
  'يرجى ادخال الكمية': 'Please enter the quantity',
  'الشروط والأحكام': 'Terms and Conditions',
  'الشحن إلى': 'Shipping to',
  'حفظ': 'Save',
  'احذف المنتج لإتمام عملية الشراء': 'Delete the product to complete the purchase',
  'قم بإضافته مرة أخرى بالضغط على المنتج': 'Add it again by clicking on the product',
  'تم تغيير سعر هذا المنتج': 'The price of this product has changed',
  'تحميل': 'download',
  'الوزن': 'Weight',
  'نعتذر ، لا يوجد محتوى لهذة الصفحة حاليا':
      'Sorry, there is no content for this page at the moment',
  'الشكاوى والاقتراحات': 'Complaints & Suggestions',
  'الأسئلة الشائعة': 'FAQ\'s',
  'نبهني عند التوفر': 'Out of quantity',
  'اختر أحد الخيارات': 'Choose an option',
  'لا يوجد منتجات حالياً': 'There are no products at the moment',
  'حاول مجدداً': 'Try again',
  'يجب ادخال تقييم أولاً': 'You must enter a rating first',
  'التراخيص': 'License',
  'حذف الحساب': 'Delete Account',
  'تم حذف الحساب بنجاح': 'Account deleted successfully',
  'هل أنت متأكد من حذف حسابك؟': 'Are you sure you want to delete your account?',
  'لا': 'No',
  'نعم': 'Yes',
  'إحذف حسابي': 'Delete my account',
  'رقم السجل التجاري': 'Commercial Registration Number',
  'جميع المنتجات': 'All Products',
  'هذا المنتج لم يعد متوفرا': 'This product is\'t available',
  'تأكيد البنك المحول له': 'Confirmation of the transferee bank',
  'الدفع عند الاستلام': 'Payment Upon Receipt',
  'بالشراكة مع': 'Copartner',
  'العنوان': 'Address',
  'إلغاء السلة': 'Cancel Cart',
  ' أضف المنتجات التي ترغب بشرائها في السلة واتمم عملية الشراء في وقت لاحق.':
      'Add the products you wish to purchase in the cart and complete the purchase at a later time. ',
  'الأقسام': 'Categories',
  'نقاط الولاء': 'Loyalty points',
  'قسيمة رقم': 'voucher key',
  'تم النسخ': 'Copied',
  'منتج رقمي': 'Digital product',
  'عذراً، حاول مجدداً بعد دقيقة': 'Please try again later after a minute',
  'لا توجد كمية إضافية كافية من هذا المنتج':
      'There is not enough additional quantity of this product',
  'المتبقي هو - @quantity - من هذا المنتج':
      'Remaining is - @quantity - From this product',
  'عرض التخفيضات فقط': 'Show discounted only',
  'يوم': 'Day',
  'إخفاء': 'Hide',
  'ساعة': 'Hour',
  'دقيقة': 'Min',
  'ثانية': 'Sec',
  'يفتح المتجر بعد': 'The store opens after',
  'نبهني عند توفر المتجر': 'Notify me when the store is available',
  'تفعيل الاشعارات': 'Activate Notifications',
  'تمت العملية بنجاح': 'Succeed',
  'نعتذر لك .. يرجى المحاولة مرة أخرى بعد لحظات ':
      'We apologize .. Please try again in few moments',
  'معفى من الضريبة': 'Exempt from tax',
  'الكمية المتوفرة : ': 'Quantity Available :',
  'المنتج الذي حاولت عرضه غير صحيح أو غير موجود حاليا تم إعادة توجيهك للصفحة الرئيسية للمتجر':
      'error The product you\'ve requested is not available at the moment, we\'ve redirected you to the store home page.',
  'تم إضافة كوبون شحن مجاني للسلة': 'Free shipping coupon applied',
  'سيتم خصم رسوم الدفع عند الاستلام': 'Free COD fees coupon applied',
  'لديك خصم في السلة أكبر من قيمة الكوبون':
      'You have a discount greater than this coupon value',
  'تصفية النتائج': 'Result Filtration',
  'مسح الفلترة': 'Clear filters',
  'أفضل الماركات': 'Best Brands',
  'سيتم ارسال هذه المنتجات كهدية': 'These products will be sent as a gift',
  'من: ': 'From: ',
  'إلى: ': 'To: ',
  'الرسالة: ': 'Message: ',
  'المنتجات سيتم تغليفها كهدية مع بطاقة اهداء':
      'Products will be gift wrapped with a gift card',
  'ستصلك الفاتورة على البريد الإلكتروني ولن ترفق مع الطلب':
      'You will receive the invoice via e-mail and will not be included with the order',
  'اسم مرسل الهدية': 'Gift sender\'s name',
  'اسم مستلم الهدية': 'Gift recipient\'s name',
  'ارفاق رابط (صورة أو فيديو)': 'Attach a link (video or audio)',
  'ارفاق رسالة': 'Attach a message',
  'تصميم البطاقة': 'Card Design',
  'معاينة': 'Review',
  'تم اضافة الطلب كهدية': 'The order has been added as a gift',
  'استفسر عن المنتج': 'Contact us about the product',
  'أرسلها كهدية': 'Send as a gift',
  'تعديل': 'Edit',
  'هذا الحقل إلزامي': 'Required Field',
  '': '',
};
